services:
  remote-browser:
    build:
      context: .
      dockerfile: Dockerfile
    image: remote-browser
    ports:
      - "3000:3000"
      - "8080:8080"
      - "41000-41050:41000-41050/udp"
    environment:
      ANNOUNCED_IP: 127.0.0.1
      DEBUG: mediasoup*
    restart: always
